### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by diasdavid** [ipfs-shipyard/proto.school#44]
For metrics //cc @mishmosh

**Comment by mikeal** [comment]
Is there a preferred analytics tool we use? @lgierth

**Comment by lgierth** [comment]
Google Analytics usually (I hate it) -- make sure to add it in a way that it's only active on https://proto.school, not on localhost:8080/ipns/proto.school or ipfs.io/ipns/proto.school

**Comment by vmx** [comment]
As a user I also dislike Google Analytics (I disabled it). I think there should be a clear plan on what we want to track and why instead of doing a "let's collect as much as possible just in case".

**Comment by mikeal** [comment]
On the Node.js website we came up with a little code snippet that disables GA when "do not track" is set in the browser as GA ignores it by default. That might be a good compromise in the short term so that we can get analytics into a tool our team is familiar with until we find a better alternative.

**Comment by lgierth** [comment]
If you're already doing a check, make it `if url.host == "proto.school"` too :) It'd be good to keep up the expectation that websites in IPFS are self-container and don't make external requests (at least when requested as /ipns/example.com or through a local gateway). And it'd be something that we can rather easily copy to all other websites that make use of GA, I guess (ipfs.io, protocol.ai, etc.)
