### ISSUE TITLE
Link to documentation from exercise

### ISSUE THREAD

**Issue by lanzafame** [ipfs-shipyard/proto.school#48]
Would be super useful if the exercises linked to the docs of the API call being taught as it can't generally be assumed the person doing the exercise will know where to find the docs. 

![proto-school-api-docs](https://user-images.githubusercontent.com/5924712/44240259-a5ca5300-a200-11e8-8652-68877762c39f.png)

**Comment by terichadbourne** [comment]
Actually, I think that like goes to command line documentation, but we're using the JS library here in the tutorials, right? At first glance, the documentation I find for JS is this, which I don't find terribly enlightening: https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/DAG.md#dagput

Are there more detailed docs for the IPFS and GO Libraries somewhere else that I should be referencing?

**Comment by mikeal** [comment]
> Are there more detailed docs for the IPFS and GO Libraries somewhere else that I should be referencing?

For JS, that's the best one. The reason it's a little generic is because there at two libraries (`js-ipfs` and `js-ipfs-api`) that try to conform to the same API. One is a full IPFS implementation and the other is an API client to a remote IPFS instance.

**Comment by terichadbourne** [comment]
@mikeal Are you suggesting suggesting linking to https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/DAG.md#dagput although the only info there is "Store an IPLD format node"? 

It looks like neither this nor the CLI documentation state clearly (or at least in terms I understand) that the command returns a CID, so I'll need to add that to the text of the workshop regardless. Is there someone responsible for these two documentation sites that would be the one to add that detail there?

**Comment by mikeal** [comment]
It's quite hard to divine from the docs, but it states `If no callback is passed, a [promise][] is returned` and then in the actual code sample you see that the callback get a `CID` instance on success.

The promise returned is for a `CID` instance. In ProtoSchool we use async functions everywhere so the promise stuff happens under the hood.

We're in an awkward place with promises vs callbacks. We know that we want to use async functions moving forward but many of the docs still favor the callback API.

Rather than trying to do a complete tutorial on promises, let's just put some basic `dag.put` documentation in the tutorial, favoring the promise API, rather than linking into the interface docs which are too confusing.

**Comment by terichadbourne** [comment]
Gotcha. I'll take a stab at this and run it by you.

**Comment by terichadbourne** [comment]
@mikeal Does the wording now used for [Basics Lesson 1](https://proto.school/#/basics/01)  make sense and give as much detail as we need it to about what the function does. The current version meets my beginner needs (i.e. lets me understand enough to pass the exercise), but doesn't do anything to explain any nuances related to promises and callbacks (which, to be honest, I still am not quite grasping from your note above). If this doesn't look right to you, let's talk through the best wording to use here.

**Comment by terichadbourne** [comment]
@mikeal When you have a sec, could you confirm whether you think more context is needed here around the promises and callbacks? (See above.) If not, this can be closed. If so, let's chat.

**Comment by mikeal** [comment]
For this one I think it's fine.

If we wanted to be hyper-specific we would say that it "returns a promise for a CID" but, in this case, that isn't really important since the promise is returned in an async function, so it gets resolved the same as if it were a value.

I'd err on the side of saying less because saying more just confuses things more.

**Comment by mikeal** [comment]
PS. I think a lot of the "promises vs callbacks" concerns here were exaggerated by the `js-ipfs` API docs, which will be changing pretty soon to favor an async await (promises) API.

**Comment by terichadbourne** [comment]
Okay, will leave as is, and am closing this issue now. If our docs improve, we can circle back and add a link out to more detailed information.
