### ISSUE TITLE
Provide section/workshop name as something you can just grab from the Vue template

### ISSUE THREAD

**Issue by terichadbourne** [ipfs-shipyard/proto.school#62]
Per my discussion with @olizilla this morning, I'd love to be able to access the section/workshop name (basics, blog, etc.) from the Vue template. Currently I believe I can only access the lesson name this way, and there could easily be duplication in lesson names across workshops. There may be other reasons we'll want this, but at the moment I'd like to embed it in a link URL so that we can pre-populate it into an issue title on GitHub when the user has questions to ask about the lesson. (WIP in the questions-link branch.) 

@olizilla or @mikeal, would either of you be game to make this change, perhaps with me looking over your shoulder as a Vue learning experience?

**Comment by mikeal** [comment]
We could pull the short names out of the URL. The URL already has a unique identifier for each lesson and step.

Basically, we'd add a method to the base template that just parsed the URL params (probably using the params inside of vuejs rather than window.URL) and we could get "workshop: blog, lesson: 01" or whatever format would be best for your.
